version: '2'
services:
    aguapotablecuicuno-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/AguaPotableCuicuno/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=AguaPotableCuicuno
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
